### ISSUE TITLE
Matching on token after refresh fails

### ISSUE THREAD

**Issue by ThomasArts** [nlfiedler/enenra#12]
I assume that matching on Token in:
https://github.com/nlfiedler/enenra/blob/fc253037cb5913700bb83cddafdd835bdbd6992c/src/enenra_server.erl#L51

is aimed to be an assignment instead. If we get a new token returned from `call_remote({refresh_token, Credentials}),` different from Token, then this gives a badmatch.

Instead one should use FreshToken as variable.

**Comment by nlfiedler** [comment]
That is almost certainly a copy/paste error on my part, and by dumb luck never ran into that case (or apparently noticed when it did). I don't have a build setup any more, so if you want to submit a PR, please feel free. Thanks.

**Comment by philipcristiano** [comment]
Can this be tagged as well? I ran into this using the `0.4.0` tag.

**Comment by nlfiedler** [comment]
Oh shoot, and this was fixed months ago, too. I've just added the tag, sorry about that.

**Comment by philipcristiano** [comment]
Thanks!
